### ISSUE TITLE
Settings resolution to 3840 x 1080 doesn't work

### ISSUE THREAD

**Issue by zXynKs** [MichaelMcDonnell/rt3conf#1]
Hi,

First off, thanks for making this tool.

When I run this command to set the resolution to for my super-wide screen monitor, it generates [this file](https://github.com/MichaelMcDonnell/rt3conf/files/6953919/engine.zip). When I run the app it doesn't work. It just reverts to 640 x 800. My guess is it's a limitation with the app but I wondered if there is anything I'm missing.
> rt3conf.exe -x 3840 -y 1080

Thanks

**Comment by MichaelMcDonnell** [comment]
Thanks for using rt3conf and reporting the issue @zXynKs! I'm happy that to hear I have a user :smile:

When I run the game at 1920x1200 (my screen's native resolution) the menu in the game says 640x480. It is running at the correct resolution which I can both see and confirm in the monitor's on-screen display. This is not what is happening on your computer? Is the picture stretched and very blocky? Note that the textures will be [rendered at a low resolution because of a bug in the game handling graphics cards with a lot of memory](http://hawkdawg.com/forums/viewtopic.php?f=5&t=3399), so look at everything else than the textures.

Otherwise, my best guess is that the game can't handle that resolution. I didn't put any restrictions in the code on purpose. The width and height are handled as two u32's which means their range is 0-4294967295 but I suspect the game only uses them as u16's, in which case the range is 0-65535. That should be well within the range 3840x1080.

I opened the `engine.cfg` file you attached with [wxHexEditor](https://sourceforge.net/projects/wxhexeditor/). The width starts at offset 4 and the values are [0x00, 0x0f, 0x00, 0x00] which is 0x00000f00 little-endian or 3840 in decimal. The height starts at offset 8 and the values are [0x38, 0x04, 0x00, 0x00] which is 0x00000438 little-endian or 1080 in decimal. So rt3conf seems to generate the right values.

I'll try to hook up my second monitor to my machine to see what happens when I try to run it the game at 3840x1200 and 3840x1080.

**Comment by MichaelMcDonnell** [comment]
I just tried NVIDIA surround to span two 1920x1200 screens. Both of the monitors reported running at their native resolution both at 3840x1200 and 3840x1080 so something doesn't work quite right with NVIDIA surround. Either way, the game looked very stretched and blurry at that aspect ratio. It looks like the game simply doesn't support ultra wide monitors. Feel free to re-open if you have new information.

**Comment by zXynKs** [comment]
Thanks @MichaelMcDonnell much appreciate your time
